# __WATER MLIP MD simulations__
Objective: generate enough sampling to determine if the experimental solvent-dependence of COSAN is observed using three different uMLIP models: UMA-small, MACE-MP-0b2 and ORB-v3. 

Secondary objective: See if in sampling the lack of rotational invariance of ORB models is diffuminated. Inspired by the ETH Zürich team regarding rotational invariance and direct force prediction. 

### __Model definitions__

In [6]:
# MACE
from mace.calculators import mace_mp

macemp = mace_mp(
    model="medium", 
    dispersion=False, 
    default_dtype="float32", 
    device='cpu',
    )

CALC_NAME = 'MACE-MP'

ModuleNotFoundError: No module named 'mace'

In [3]:
# ORB
from orb_models.forcefield.pretrained import orb_v3_conservative_inf_omat, orb_v2
from orb_models.forcefield.calculator import ORBCalculator

orbff_v2 = orb_v2(device='cpu')
orb_calc_v2 = ORBCalculator(orbff_v2, device='cpu')

#orbff_v3 = orb_v3_conservative_inf_omat(device='cpu')
#orbff_v3_calc = ORBCalculator(orbff_v3, device='cpu')

CALC_NAME = 'ORB'

/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/site-packages/orb_models/utils.py:30: UserWarning: Setting global torch default dtype to torch.float32.
  warnings.warn(f"Setting global torch default dtype to {torch_dtype}.")


In [ ]:
# UMA
from fairchem.core import FAIRChemCalculator
from fairchem.core.units.mlip_unit import load_predict_unit

# define the UMA ASE calculator
uma_predictor = load_predict_unit(
    path='/Users/sergiortizropero/TFG_phys/NNPs_TFG/models/ase_uma/uma-s-1p1.pt', 
    device='cpu',                   
    inference_settings='default',   
)
uma_calc = FAIRChemCalculator(
    uma_predictor,
    task_name='omol',               
)

CALC_NAME = 'UMA'

/Users/sergiortizropero/miniconda3/envs/ASE_UMA_test/lib/python3.12/site-packages/torchtnt/utils/version.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
W0718 11:51:27.198000 84253 site-packages/torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.


### __Imports & Functions__

In [25]:
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
#rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
rc('text', usetex=True)
rc('lines', lw=1, color='b')
rc('legend', loc='best')
plt.rcParams["legend.fancybox"] = False
plt.rcParams["legend.edgecolor"] = 'black'
plt.rcParams['legend.borderpad'] = 0.25
plt.rcParams['legend.fontsize'] = 11
plt.rcParams.update({'pgf.preamble': r'\usepackage{amsmath}'})

from ase.visualize import view
from ase.build import molecule
from ase.io import write, read
from ase.io import Trajectory, trajectory
from ase import build
from ase.data.pubchem import pubchem_atoms_search

import ase.units as units
from ase import Atoms
from ase.calculators.tip3p import TIP3P, angleHOH, rOH
from ase.constraints import FixBondLengths
from ase.io.trajectory import Trajectory
from ase.io.trajectory import TrajectoryReader
from ase.md import Langevin, VelocityVerlet
from ase.optimize import BFGS
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution
from ase.calculators.tip3p import angleHOH, rOH
import pickle
import ase.io
from tqdm import tqdm

try:
    import cmocean
    cmap = cmocean.cm.balance   
except:
    cmap = 'seismic'

In [ ]:
def prepare_water(save_path, sim_name, T_0, pbc=False, box_size=None):

    x = angleHOH * np.pi / 180 / 2
    pos = [
        [0, 0, 0],
        [0, rOH * np.cos(x), rOH * np.sin(x)],
        [0, rOH * np.cos(x), -rOH * np.sin(x)],
    ]
    atoms = Atoms('OH2', positions=pos)
    

    # add calculator
    if CALC_NAME == 'MACE-MP':
        atoms.calc = macemp
    elif CALC_NAME == 'ORB':
        #atoms.calc = orbff_v3_calc
        atoms.calc = orb_calc_v2
    elif CALC_NAME == 'UMA':
        atoms.calc = uma_calc
    else:
        raise ValueError('name of the calculation not identified!')

    # system preprocessing
    if box_size is not None:
        atoms.set_cell(box_size)
    else:
        atoms.set_cell((20, 20, 20))
    atoms.center()

    if pbc:
        atoms.set_pbc(True)

    # path setup
    sim_path = os.path.join(save_path, sim_name)

    if not os.path.exists(sim_path):
        os.makedirs(sim_path)

    # initialize velocities
    MaxwellBoltzmannDistribution(atoms, temperature_K=T_0)

    return atoms


def load_water_box(save_path, sim_name, T_0, pbc=False, box_size=None):

    
    water_box_pdb = '/Users/sergiortizropero/TFG_phys/NNPs_TFG/COSAN/simulations/water_mds/water_box.pdb'
    atoms = read(water_box_pdb)
    atoms.info = {
        'spin': 1,
        'charge': 0,
        'k': 0,
    }

    # add calculator
    if CALC_NAME == 'MACE-MP':
        atoms.calc = macemp
    elif CALC_NAME == 'ORB':
        #atoms.calc = orbff_v3_calc
        atoms.calc = orb_calc_v2
    elif CALC_NAME == 'UMA':
        atoms.calc = uma_calc
    else:
        raise ValueError('name of the calculation not identified!')

    # system preprocessing
    if box_size is not None:
        atoms.set_cell(box_size)
    else:
        atoms.set_cell((20, 20, 20))
    atoms.center()

    if pbc:
        atoms.set_pbc(True)

    # path setup
    sim_path = os.path.join(save_path, sim_name)

    if not os.path.exists(sim_path):
        os.makedirs(sim_path)

    # initialize velocities
    MaxwellBoltzmannDistribution(atoms, temperature_K=T_0)

    return atoms




def run_NVT(atoms, length, dt, T, sim_path, sim_name, k, save_int=100, overwrite=False):

    # define paths
    log_path = os.path.join(sim_path, sim_name + f'_{k}.log')
    traj_path = os.path.join(sim_path, sim_name + f'_{k}.traj')

    # NVT run
    md = Langevin(
        atoms,
        dt*units.fs,
        temperature_K=T,
        friction=0.01,
        logfile=log_path,
        loginterval=save_int,
    )

    # trajectory
    if os.path.exists(traj_path) and (not overwrite):
        raise ValueError('Trajectory file already exists!')
    traj = Trajectory(traj_path, 'w', atoms)

    # save every save_int steps
    md.attach(traj.write, interval=save_int)
    md.run(length)
    print(f'md {k} has finished')

    return atoms


def restart_md(pkl_path, verbose=True):
    
    with open(pkl_path, 'rb') as f:
        cosan_restart = pickle.load(f)

    if verbose:
        print('restarting with Atoms.object with properties:')
        print(cosan_restart.info['charge'])
        print(cosan_restart.info['spin'])
        print(cosan_restart.info['k'])
        print(cosan_restart.info['positions'])
        print(cosan_restart.info['velocities'])

    return cosan_restart



def relax_structure(atoms, sim_path, convergence=2):
    dyn = BFGS(atoms, trajectory=os.path.join(sim_path, 'relaxation.traj'))
    dyn.run(fmax=convergence)

# __WATER MD__

In [30]:
K = 1              # number of fragments
length = 100000       # in steps
dt = 1              # in fs
T_init = 300.       # in K
T_target = 300.     # in K
save_int = 100

ps_length = float(K * length * dt / 1000)
sim_name = f'single_{CALC_NAME}_{ps_length:.1f}'
#sim_name = 'test'
save_path = '/Users/sergiortizropero/TFG_phys/NNPs_TFG/COSAN/simulations/water_mds'
sim_path = os.path.join(save_path, sim_name)


# build the waters
water = prepare_water( 
    save_path, 
    sim_name, 
    T_init,
)
water.info = {
    'spin': 1,
    'charge': 0,
    'k': 0,
}

restart = False
restart_file = ''

print(f'restarting: {restart}')
print(sim_name)
print('Performing WATER {:.1f} ps NVT MD @ {} K'.format(ps_length, T_target))

restarting: False
single_ORB_100.0
Performing WATER 100.0 ps NVT MD @ 300.0 K


In [8]:
if restart:
    # retreive latest pickle.
    water = restart_md(restart_file, verbose=True)

converged = False
while not converged: 

    # start with k = 0
    # add 1
    water.info['k'] += 1
    k = water.info['k']

    # run a fragment
    # simulate k = 1
    run_NVT(
        water, 
        length, 
        dt, 
        T=T_target, 
        sim_path=sim_path, 
        sim_name=sim_name, 
        k=k, 
        save_int=save_int, 
        overwrite=restart,
    )

    # save to a file
    water.info['positions'] = water.get_positions()
    water.info['velocities'] = water.get_velocities()
    print(water.info['positions'])
    print(water.info['velocities'])
    print(water.info['k'])

    with open(os.path.join(sim_path, sim_name+f'_{k}_water.pkl'), 'wb') as f:
        pickle.dump(water, f)

    # check convergence
    if water.info['k'] >= K:
        converged = True

md 1 has finished
[[ 8.23264942 10.33572058  5.06421283]
 [ 8.01836384 11.30792118  5.01512394]
 [ 7.45517322  9.85504983  5.12336827]]
[[ 0.03543437 -0.00939162 -0.00771233]
 [-0.48527241 -0.09335905 -0.17485353]
 [-0.07714288  0.24242306  0.29726402]]
1


# __WATER BOX MD__

In [39]:
K = 1              # number of fragments
length = 1000       # in steps
dt = 1              # in fs
T_init = 300.       # in K
T_target = 300.     # in K
save_int = 100


ps_length = float(K * length * dt / 1000)
sim_name = f'solvated_{CALC_NAME}_{ps_length:.1f}'
#sim_name = 'test'
save_path = '/Users/sergiortizropero/TFG_phys/NNPs_TFG/COSAN/simulations/water_mds'
sim_path = os.path.join(save_path, sim_name)

# build the waters
waters = load_water_box( 
    save_path, 
    sim_name, 
    T_init,
    #box_size=(18.774, 18.774, 18.774),
    box_size=(20, 20, 20),
    pbc=True,
)
waters.info = {
    'spin': 1,
    'charge': 0,
    'k': 0,
}

restart = False
restart_file = ''

print(f'restarting: {restart}')
print(sim_name)
print('Performing WATER {:.1f} ps NVT MD @ {} K'.format(ps_length, T_target))

restarting: False
solvated_ORB_1.0
Performing WATER 1.0 ps NVT MD @ 300.0 K


In [40]:
relax_structure(waters, sim_path)
with open(os.path.join(sim_path, 'optimized.pkl'), 'wb') as f:
        pickle.dump(waters, f)

if restart:
    # retreive latest pickle.
    waters = restart_md(restart_file, verbose=True)

converged = False
while not converged: 

    # start with k = 0
    # add 1
    waters.info['k'] += 1
    k = waters.info['k']

    # run a fragment
    # simulate k = 1
    run_NVT(
        waters, 
        length, 
        dt, 
        T=T_target, 
        sim_path=sim_path, 
        sim_name=sim_name, 
        k=k, 
        save_int=save_int, 
        overwrite=restart,
    )

    # save to a file
    waters.info['positions'] = waters.get_positions()
    waters.info['velocities'] = waters.get_velocities()
    print(waters.info['positions'])
    print(waters.info['velocities'])
    print(waters.info['k'])

    with open(os.path.join(sim_path, sim_name+f'_{k}_water.pkl'), 'wb') as f:
        pickle.dump(waters, f)

    # check convergence
    if waters.info['k'] >= K:
        converged = True

      Step     Time          Energy          fmax
BFGS:    0 18:36:40    -2445.266113      192.170619
BFGS:    1 18:36:42    -2769.355469       68.290928
BFGS:    2 18:36:44    -3073.040527       43.921440
BFGS:    3 18:36:46    -3309.744873       57.859860
BFGS:    4 18:36:49    -3415.162109       22.183399
BFGS:    5 18:36:51    -3509.240723       10.359201
BFGS:    6 18:36:53    -3573.539551       12.053555
BFGS:    7 18:36:55    -3610.803711        6.180288
BFGS:    8 18:36:57    -3636.064941        4.585664
BFGS:    9 18:36:59    -3653.512695        3.840438
BFGS:   10 18:37:01    -3665.206787        7.465894
BFGS:   11 18:37:04    -3674.994385        5.969211
BFGS:   12 18:37:06    -3682.318604        6.232806
BFGS:   13 18:37:08    -3688.445312        2.745205
BFGS:   14 18:37:10    -3693.501953        3.009447
BFGS:   15 18:37:12    -3698.472168        3.233088
BFGS:   16 18:37:15    -3703.159180        2.224850
BFGS:   17 18:37:17    -3706.545898        1.696418
BFGS:   18 18:

In [38]:
# visualize the traj
traj_path = '/Users/sergiortizropero/TFG_phys/NNPs_TFG/COSAN/simulations/water_mds/solvated_ORB_0.0/solvated_ORB_0.0_1.traj'

load_traj = Trajectory(traj_path, 'r')
view(load_traj, viewer='ase')

<Popen: returncode: None args: ['/Users/sergiortizropero/miniconda3/envs/ASE...>

Traceback (most recent call last):
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/site-packages/ase/gui/pipe.py", line 32, in <module>
    main()
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/site-packages/ase/gui/pipe.py", line 28, in main
    plt.show()
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/site-packages/matplotlib/pyplot.py", line 614, in show
    return _get_backend_mod().show(*args, **kwargs)
  File "/Users/sergiortizropero/miniconda3/envs/ASE_orbital/lib/python3.10/site-packages/matplotlib_inline/backend_inline.py", line 90, in show
    display(
  File "/Users/sergiortizropero/miniconda3/env